/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_youxing_common_utils_NativeTool */

#ifndef _Included_com_youxing_common_utils_NativeTool
#define _Included_com_youxing_common_utils_NativeTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_youxing_common_utils_NativeTool
 * Method:    a
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_youxing_common_utils_NativeTool_a
  (JNIEnv *, jclass);

/*
 * Class:     com_youxing_common_utils_NativeTool
 * Method:    ne
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_youxing_common_utils_NativeTool_ne
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
